/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms;

import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author aboyb
 */
public class IndexAdmin extends javax.swing.JFrame {

    /**
     * Creates new form IndexAdmin
     */
    public IndexAdmin() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setPaddingLabel();
    }
    
    private void setPaddingLabel() {
        
        
        lblCat.setBorder(new EmptyBorder(10,20,10,20));//top,left,bottom,right
        lblCat.setOpaque(true);
        lblCat.setBackground(Color.YELLOW);

        lblCustomer.setBorder(new EmptyBorder(10,20,10,20));//top,left,bottom,right
        lblCustomer.setOpaque(true);
        lblCustomer.setBackground(Color.YELLOW);

        lblProduct.setBorder(new EmptyBorder(10,20,10,20));//top,left,bottom,right
        lblProduct.setOpaque(true);
        lblProduct.setBackground(Color.YELLOW);
        
        lblVoucher.setBorder(new EmptyBorder(10,20,10,20));//top,left,bottom,right
        lblVoucher.setOpaque(true);
        lblVoucher.setBackground(Color.YELLOW);
        
        lblAnalytics.setBorder(new EmptyBorder(10,20,10,20));//top,left,bottom,right
        lblAnalytics.setOpaque(true);
        lblAnalytics.setBackground(Color.YELLOW);
        
        lblStaffs.setBorder(new EmptyBorder(10,20,10,20));//top,left,bottom,right
        lblStaffs.setOpaque(true);
        lblStaffs.setBackground(Color.YELLOW);


    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();
        lblCat = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblAnalytics = new javax.swing.JLabel();
        lblStaffs = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblVoucher = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Admin Manager");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblCat.setBackground(new java.awt.Color(255, 255, 0));
        lblCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCat.setText("Manage Categories");
        lblCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCatMouseClicked(evt);
            }
        });

        lblProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProduct.setText("Manage Products");
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductMouseClicked(evt);
            }
        });

        lblAnalytics.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAnalytics.setText("Analytics");
        lblAnalytics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnalyticsMouseClicked(evt);
            }
        });

        lblStaffs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStaffs.setText("Manage Staffs");
        lblStaffs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStaffsMouseClicked(evt);
            }
        });

        lblCustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCustomer.setText("Manage Customers");
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
        });

        lblVoucher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVoucher.setText("Manage Vouchers");
        lblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoucherMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCat, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(105, 105, 105)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(111, 111, 111)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStaffs, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCat)
                    .addComponent(lblProduct)
                    .addComponent(lblAnalytics))
                .addGap(68, 68, 68)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoucher)
                    .addComponent(lblCustomer)
                    .addComponent(lblStaffs))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCatMouseClicked
        setVisible(false);
        (new ManageCategory()).setVisible(true);
    }//GEN-LAST:event_lblCatMouseClicked

    private void lblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseClicked
        setVisible(false);
        (new ManageProduct()).setVisible(true);
    }//GEN-LAST:event_lblProductMouseClicked

    private void lblAnalyticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnalyticsMouseClicked
        this.dispose();
        (new Analytics()).setVisible(true);
    }//GEN-LAST:event_lblAnalyticsMouseClicked

    private void lblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoucherMouseClicked
        this.dispose();
        (new ManageVoucher()).setVisible(true);
    }//GEN-LAST:event_lblVoucherMouseClicked

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked
        this.dispose();
        (new ManageCustomer()).setVisible(true);
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblStaffsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStaffsMouseClicked
        this.dispose();
        (new ManageStaff()).setVisible(true);
    }//GEN-LAST:event_lblStaffsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAnalytics;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblStaffs;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnHeader;
    // End of variables declaration//GEN-END:variables
}
